baseURL = 'https://example.org/'
languageCode = 'no-nb'
title = 'Claudbakks Bryllop'
theme = 'alpha-church'

[params]
title = "Christine og Taralds bryllup"
subtutle = "DET SCHMELLER PÅ KOSTER"
instant_page = true
[params.map]
service = "osm"
latitude = "58.89378"
longitude = "11.04860"
zoom = "11"

[params.banner]
image = "/img/sunset.jpeg"
