baseURL = 'https://example.org/'
languageCode = 'no-nb'
title = 'Claudbakks Bryllop'
theme = 'alpha-church'

[params]
title = "Christine og Taralds bryllup"
subtutle = "DET SCHMELLER PÅ KOSTER"
instant_page = true
[params.map]
service = "osm"
latitude = "58.89378"
longitude = "11.04860"
zoom = "11"

[params.banner]
    image = "/img/sunset.jpeg"


[menu]
    [[menu.main]]
        name = "Hjem"
        url = "/"
        weight = 1
    [[menu.main]]
        name = "Om Koster"
        url = "/om_koster"
        weight = 2
    [[menu.main]]
        name = "Program"
        url = "/program"
        weight = 3
    [[menu.main]]
        name = "Praktisk Informasjon"
        url = "/praktisk"
        weight = 4
    [[menu.main]]
        name = "Aktiviteter"
        url = "/aktiviteter"
        weight = 5
    [[menu.main]]
        name = "Historien om oss"
        url = "/tidslinje"
        weight = 5
    [[menu.main]]
        name = "Ønskeliste"
        url = "/onskeliste"
        weight = 6

[markup.goldmark.renderer]
unsafe = true # Allows embedded html, I want maps
